FROM alpine:3.13

ENV UID=1337 \
    GID=1337

RUN apk add --no-cache ffmpeg su-exec ca-certificates bash jq curl yq

ARG EXECUTABLE=./matrix-pulsesms
COPY $EXECUTABLE /usr/bin/matrix-pulsesms
COPY ./example-config.yaml /opt/matrix-pulsesms/example-config.yaml
COPY ./docker-run.sh /docker-run.sh
VOLUME /data

CMD ["/docker-run.sh"]
